apiVersion: v1
kind: PersistentVolume
metadata:
name: pv-image-registry 
spec:
capacity:
    storage: 100Gi 
accessModes:
- ReadWriteMany 
nfs: 
    path: /path/to/nfs/image-registry  
    server: 192.168.88.7 
persistentVolumeReclaimPolicy: Retain 